# Generated by Django 5.2.3 on 2025-06-20 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('estoque_minimo', models.PositiveIntegerField(default=10, verbose_name='Estoque Minimo')),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Controle de Estoque',
                'verbose_name_plural': 'Controles de Estoque',
            },
        ),
    ]
