# Generated by Django 5.2.3 on 2025-06-25 04:51

from django.db import migrations
import os

def cria_superusuario(apps, schema_editor):
    User = apps.get_model('auth', 'User')

    username = os.environ.get('ADMIN_USER')
    email = os.environ.get('ADMIN_EMAIL')
    password = os.environ.get('ADMIN_PASS')

    if username and email and password:
        if not User.objects.filter(usrname=username).exists():
            User.objects.create_superuser(
                username=username,
                email=email,
                password = password,
            )
            print(f"Superusuario '{username}' criado com sucesso.")
        else:
            print(f"Superusuario '{username}' já existe, não foi criado novamente.")

class Migration(migrations.Migration):

    dependencies = []

    operations = [
        migrations.RunPython(cria_superusuario),
    ]
